local ReplicatedStorage = game:GetService("ReplicatedStorage")

local Worlds = require(ReplicatedStorage.Shared.ECS.Worlds)

-------------------------------------------------------------------------------
-- CONSTANTS
-------------------------------------------------------------------------------

local WORLD = Worlds.Default

-------------------------------------------------------------------------------
-- RETURN
-------------------------------------------------------------------------------

return {}
