local ReplicatedStorage = game:GetService("ReplicatedStorage")
-------------------------------------------------------------------------------
-- CONSTANTS
-------------------------------------------------------------------------------

local CONTROLLERS = ReplicatedStorage.Client.Controllers

-------------------------------------------------------------------------------
-- RETURN
-------------------------------------------------------------------------------

return { CONTROLLERS.ConveyorController } :: { ModuleScript }
